## This configuration was generated by terraform-provider-oci

resource "oci_artifacts_container_configuration" "export_container_configuration" {
  compartment_id                      = var.compartment_ocid
  is_repository_created_on_first_push = "false"
}
