## This configuration was generated by terraform-provider-oci

data "oci_identity_availability_domain" "export_BUkv-AP-TOKYO-1-AD-1" {
  compartment_id = var.compartment_ocid
  ad_number      = "1"
}
