## This configuration was generated by terraform-provider-oci

resource "oci_core_nat_gateway" "export_NAT--myvcn" {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  display_name   = "NAT-Gateway-myvcn"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_myvcn.id
}

resource "oci_core_internet_gateway" "export_--myvcn" {
  compartment_id = var.compartment_ocid
  display_name   = "Internet-Gateway-myvcn"
  enabled        = "true"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_myvcn.id
}

resource "oci_core_vcn" "export_myvcn" {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  display_name   = "myvcn"
  dns_label      = "myvcn"
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
  security_attributes = {
  }
}

resource "oci_core_subnet" "export_--myvcn_1" {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block      = "10.0.0.0/24"
  compartment_id  = var.compartment_ocid
  dhcp_options_id = oci_core_vcn.export_myvcn.default_dhcp_options_id
  display_name    = "Public-Subnet-myvcn"
  dns_label       = "sub10160457000"
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_myvcn.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_myvcn.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_myvcn.id
}

resource "oci_core_subnet" "export_--myvcn_2" {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block      = "10.0.1.0/24"
  compartment_id  = var.compartment_ocid
  dhcp_options_id = oci_core_vcn.export_myvcn.default_dhcp_options_id
  display_name    = "Private-Subnet-myvcn"
  dns_label       = "sub10160457001"
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_--myvcn-_1.id
  security_list_ids = [
    oci_core_security_list.export_--myvcn-.id,
  ]
  vcn_id = oci_core_vcn.export_myvcn.id
}

resource "oci_core_default_dhcp_options" "export_Default-DHCP-Options-for-myvcn" {
  compartment_id             = var.compartment_ocid
  display_name               = "Default DHCP Options for myvcn"
  domain_name_type           = "CUSTOM_DOMAIN"
  manage_default_resource_id = oci_core_vcn.export_myvcn.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "myvcn.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource "oci_core_security_list" "export_--myvcn-" {
  compartment_id = var.compartment_ocid

  display_name = "Private-Subnet-myvcnのセキュリティ・リスト"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_myvcn.id
}

resource "oci_core_default_security_list" "export_Default-Security-List-for-myvcn" {
  compartment_id = var.compartment_ocid
  display_name   = "Default Security List for myvcn"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_myvcn.default_security_list_id
}

resource "oci_core_route_table" "export_--myvcn-_1" {
  compartment_id = var.compartment_ocid
  display_name   = "Private-Subnet-myvcnのルート表"
  vcn_id         = oci_core_vcn.export_myvcn.id
}

resource "oci_core_default_route_table" "export_default-route-table-for-myvcn" {
  compartment_id             = var.compartment_ocid
  display_name               = "default route table for myvcn"
  manage_default_resource_id = oci_core_vcn.export_myvcn.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_--myvcn.id
    #route_type = <<Optional value not found in discovery>>
  }
}


