## This configuration was generated by terraform-provider-oci

resource oci_functions_application export_oci-devops-handson-app {
  compartment_id = var.compartment_ocid
  config = {
  }
  display_name = "oci-devops-handson-app"
  freeform_tags = {
  }
  network_security_group_ids = [
  ]
  shape = "GENERIC_X86"
  subnet_ids = [
    oci_core_subnet.export_--myvcn_1.id,
  ]
  syslog_url = ""
  trace_config {
    domain_id  = ""
    is_enabled = "false"
  }
}

