## This configuration was generated by terraform-provider-oci

resource oci_ons_subscription export_subscription {
  compartment_id = var.compartment_ocid
  delivery_policy = "{\"backoffRetryPolicy\":{\"maxRetryDuration\":7200000,\"policyType\":\"EXPONENTIAL\"}}"
  endpoint        = var.email
  freeform_tags = {
  }
  protocol = "EMAIL"
  topic_id = oci_ons_notification_topic.export_oci-devops-handson_1.id
}

resource oci_ons_notification_topic export_oci-devops-handson_1 {
  compartment_id = var.compartment_ocid
  #description = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "oci-devops-handson"
}

